# fly.toml app configuration file generated for nuxt3-kitchen-sink on 2025-04-23T16:04:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nuxt3-kitchen-sink'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.domains]]
    name = "p-nuxt3-kitchen-sink.codeblitz.net"
    catch_all = true
      
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
